#pragma once
#include "Assets/common.h"
#include "WorldManager.h"

#include "Assets/Camera.h"
#include "Assets/Shader.h"
#include "Assets/ObjShape.h"
#include "Assets/LightObj.h"
#include "Assets/Textures/CubemapTexture.h"
#include "Assets/Textures/Texture.h"
#include "Assets/Object.h"
#include <list>
#include "Assets/Collider.h"
#include "Assets/ParticleSystem.h"
#include <iostream>
#include <vector>
#include "GL/gl3w.h"
#include "GLFW/glfw3.h"
#include "glm/glm.hpp"
#include "glm/gtc/type_ptr.hpp"
#include "glm/gtx/string_cast.hpp"
#include "glm/gtx/transform.hpp"
#include <fstream>
#include "Assets/SpeedPad.h"
#include "Assets/SphereCollider.h"
#include "CubeCollider.h"
#include "OBBCollider.h"
#include "Assets/PlaneCollider.h"
#include "Assets/PlayerScript.h"
